---
- name: Define hosts
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache and install pip.
      ansible.builtin.apt:
        name: python3-pip
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  roles:
    - role: staticdev.pyenv
    - role: .
