---
roles:
  - name: staticdev.pyenv
    version: 2.5.0
  - name: gantsign.visual-studio-code
    version: 6.7.0
    when: "{{ install_vscode }}"

collections:
  - name: community.general
    version: 4.1.0
