---
roles:
  - name: staticdev.pyenv
    version: 2.4.1
  - name: gantsign.visual-studio-code
    version: 6.6.0
    when: "{{ install_vscode }}"

collections:
  - name: community.general
    version: 3.5.0
