---
- name: Install pyenv
  include_role:
    name: staticdev.pyenv
  vars:
    pyenv_owner: "{{ ansible_env.USER }}"
    pyenv_path: "{{ ansible_env.HOME }}/pyenv"
    pyenv_global: "{{ pyenv_global }}"
    pyenv_python_versions: "{{ pyenv_python_versions }}"
    pyenv_virtualenvs: []
  when: pyenv_python_versions

- name: Ensure venv installed
  package:
    name: python3-venv
    state: present
  become: true

- name: Check if pipx is installed
  command: "{{ ansible_env.HOME }}/.local/bin/pipx --version"
  register: pipx_version_cmd
  changed_when: false
  ignore_errors: true

- name: Install pipx
  pip:
    name: pipx
    extra_args: --user
  when: pipx_version_cmd is failed

- name: Check if pre-commit is installed
  stat:
    path: "{{ ansible_env.HOME }}/.local/pipx/venvs/pre-commit"
  register: pre_commit_folder_check

- name: Install pre-commit
  command: pipx install pre-commit
  register: output
  when: pre_commit_folder_check is failed

- name: Check if cookiecutter is installed
  stat:
    path: "{{ ansible_env.HOME }}/.local/pipx/venvs/cookiecutter"
  register: cookiecutter_folder_check

- name: Install cookiecutter
  command: pipx install cookiecutter
  register: output
  when: cookiecutter_folder_check is failed

- name: Check if poetry is installed
  command: "{{ ansible_env.HOME }}/.poetry/bin/poetry"
  register: poetry_cmd
  changed_when: false
  ignore_errors: true

- name: Download poetry installer
  get_url:
    url: https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
    dest: "{{ ansible_env.HOME }}/get-poetry.py"
    mode: "0400"
  when: poetry_cmd is failed
  notify: delete poetry installer

- name: Install poetry
  command: "python3 {{ ansible_env.HOME }}/get-poetry.py"
  when: poetry_cmd is failed

- name: Check if nox is installed
  stat:
    path: "{{ ansible_env.HOME }}/.local/pipx/venvs/nox"
  register: nox_folder_check

- name: Install nox
  command: pipx install nox
  when: nox_folder_check is failed

- name: Install nox-poetry
  command: pipx inject nox nox-poetry
  when: nox_folder_check is failed

- name: Install pycharm
  include_tasks: pycharm.yml
  when: install_pycharm

- name: Install vscode
  include_tasks: vscode.yml
  when: install_vscode
