---
- name: Converge
  hosts: all

  become: true

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  tasks:
    - name: "Include staticdev.python_developer"
      ansible.builtin.include_role:
        name: "staticdev.python_developer"
