---
- name: Converge
  hosts: all

  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  tasks:
    - name: "Include ansible-role-python-developer"
      include_role:
        name: "ansible-role-python-developer"
      vars:
        install_vscode: true
        vscode_extensions:
          - shan.code-settings-sync
